### ISSUE TITLE
IA quebra o jogo quando se encontra sem movimento possível

### ISSUE THREAD

**Issue by teixeira-pedro** [junglejf/Damas#12]
Quando ocorre uma situação onde *todas* as pedras remanescentes pertencentes à IA não puderem se movimentar, a aplicação quebra. Onde na verdade deveria ser dado o fim de jogo, e a vitória a quem tiver mais pedras em jogo. Vale ressaltar que quando isto ocorre com o usuário, a aplicação encerra o jogo devidamente.

**Comment by assadfelipe** [comment]
Problema consertado!
